name: build
on:
  push:
    paths-ignore:
    - 'README.org'
    - '.guix-authorizations'
    - '.guix-channel'
  pull_request:
  schedule:
    # weekly builds, making sure everything still works with guix-proper
    - cron:  '39 3 * * 0'
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      # building independent packages, don’t abort entire build if one fails
      fail-fast: false
      matrix:
        package:
          - rust-bin
    steps:
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/guix
          # use a key that (almost) never matches
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (list (channel
                   (name 'guix)
                   (url "https://github.com/declantsien/guix")
                   (branch "master")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
                  (channel
                   (name 'nonguix)
                   (url "https://gitlab.com/nonguix/nonguix")
                   (branch "master")
                   (introduction
                    (make-channel-introduction
                     "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
                     (openpgp-fingerprint
                      "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint package
        run: |
          GUIX_PROFILE="/home/runner/.config/guix/current"
          . "$GUIX_PROFILE/etc/profile"
          guix lint -L ./channel ${{ matrix.package }} |& sed -nre 's#(.*):([0-9]+):([0-9]+): (.*)$#::warning file=\1,line=\2,col=\3::\4#gp'
      - name: Build package
        run: |
          GUIX_PROFILE="/home/runner/.config/guix/current"
          . "$GUIX_PROFILE/etc/profile"
          guix build -L ./channel ${{ matrix.package }}
